# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

sitemap:
    path: sitemap.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar:
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
github: yunlzheng
weibo:
